/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppShell {
    }
}
declare global {
    interface HTMLAppShellElement extends Components.AppShell, HTMLStencilElement {
    }
    var HTMLAppShellElement: {
        prototype: HTMLAppShellElement;
        new (): HTMLAppShellElement;
    };
    interface HTMLElementTagNameMap {
        "app-shell": HTMLAppShellElement;
    }
}
declare namespace LocalJSX {
    interface AppShell {
    }
    interface IntrinsicElements {
        "app-shell": AppShell;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-shell": LocalJSX.AppShell & JSXBase.HTMLAttributes<HTMLAppShellElement>;
        }
    }
}
